import React from "react";
import "./style/knowmore.css";

const Disclaimer = () => {
  return (
    <div className="fullScreenContainer">
      <div className="infocontainer">
        <div className="infoBoard2">
          <div>
            <p className="infotext">Disclaimer</p>
            <p className="infosubtext">
              This application is a college project developed for academic
              purposes only. The information and results provided by the brain
              tumor detection model are not intended to serve as a substitute
              for professional medical advice, diagnosis, or treatment.
            </p>
            <p className="infosubtext">
              Users should consult a qualified healthcare provider for any
              health concerns. The predictions generated by this tool should not
              be solely relied upon for making clinical decisions.
            </p>
            <p className="infosubtext">
              The creators and associated institutions are not liable for any
              outcomes resulting from the use or misuse of this application.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimer;
